# Generated by Django 5.2.1 on 2025-06-01 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('selected_columns', models.JSONField(blank=True, default=list)),
                ('cleaning_options', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(max_length=50)),
                ('x_column', models.CharField(max_length=255)),
                ('y_column', models.CharField(blank=True, max_length=255, null=True)),
                ('chart_image', models.ImageField(blank=True, null=True, upload_to='charts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('csv_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.csvfile')),
            ],
        ),
    ]
