# Generated by Django 5.1.4 on 2025-06-05 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=100)),
                ('y_column', models.CharField(max_length=255)),
                ('x_columns', models.JSONField(default=list)),
                ('model_file', models.FileField(upload_to='ml_models/')),
                ('is_classifier', models.BooleanField(default=False)),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('csv_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.csvfile')),
            ],
        ),
    ]
